import Head from "next/head";
import styles from "./home.module.css";
import { Box, Button } from "@chakra-ui/react";
import { useRouter } from "next/router";
import Navbar from "./components/navbar";
import Jobs from "./components/jobs";
import Headline from "./components/headline";
import Education from "./components/education";

const Home = () => {
  return (
    <>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Headline />

      <Box className={styles["container-page"]}>
        <Jobs />
        <Education />
      </Box>
    </>
  );
};

export default Home;
