import Head from "next/head";
import styles from "./home.module.css";
import { Box, Heading } from "@chakra-ui/react";
import { useRouter } from "next/router";

const Home = () => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box>
        <Heading as="h1" size="md" onClick={() => router.push("/jobs")}>
          Riwayat Pekerjaan
        </Heading>
      </Box>
    </>
  );
};

export default Home;
