import Head from "next/head";
import styles from "./home.module.css";
import { Box } from "@chakra-ui/react";
import Navbar from "./components/navbar";
import Jobs from "./components/jobs";
import Headline from "./components/headline";
import Education from "./components/education";
import Certification from "./components/certification";
import { isMobileHandler } from "../helpers/responsive";
import MobileNavbar from "./components/navbar/mobile";

const Home = () => {
  const isMobile = isMobileHandler();
  return (
    <>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {isMobile ? <MobileNavbar /> : <Navbar />}
      <Headline />

      <Box className={styles["container-page"]}>
        <Jobs />
        <Education />
        <Certification />
      </Box>
    </>
  );
};

export default Home;
